{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-controller
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-controller
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
{{- end }}
